# Generated by Django 3.2.3 on 2021-05-30 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appWeb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacunas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idMascota', models.CharField(max_length=10)),
                ('nombreVac', models.CharField(max_length=50)),
                ('fechaVac', models.DateField()),
                ('enfermedad', models.CharField(max_length=50)),
                ('cantidadVac', models.CharField(max_length=2)),
            ],
        ),
    ]
